---
on:
  - push

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  job-default:
    uses: novoserve/github-workflows/.github/workflows/lint-dockerfile.yml@main

  job-config-file:
    uses: novoserve/github-workflows/.github/workflows/lint-dockerfile.yml@main
    with:
      config-file: tests/hadolint.yml

  job-dockerfile:
    uses: novoserve/github-workflows/.github/workflows/lint-dockerfile.yml@main
    with:
      file: tests/Dockerfile

  job-recursive:
    uses: novoserve/github-workflows/.github/workflows/lint-dockerfile.yml@main
    with:
      recursive: true

  job-recursive-greedy:
    uses: novoserve/github-workflows/.github/workflows/lint-dockerfile.yml@main
    with:
      recursive-greedy: true
