---
on:
  - push

jobs:
  job:
    uses: potherca-bot/reusable-workflows-callee/.github/workflows/validate-composer.yml@main
    with:
      check-lock: false
      check-publish: false
      strict: false
